name: CI/CD Frontend (EKS)

on:
  push:
    branches: [ "main" ]


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: AWS Credentials 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Amazon ECR 로그인
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Install dependencies and Build
        run: |
          npm install
          npm run build  # 실행 후 최상위에 dist/ 폴더가 생성됨
          
      - name: Docker 이미지 빌드 및 푸시
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: argocd/front-service 
        run: |
          # 태그 생성 시 변수 사이에 슬래시(/)가 하나만 들어가도록 확인
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest -f Dockerfile .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      # - name: K8s 매니페스트 이미지 태그 업데이트
      #   run: |
      #     # frontend 배포용 yaml 파일 경로를 입력하세요
      #     sed -i "s|image:.*|image: ${{ env.IMAGE }}|g" kubernetes/front-deploy.yaml

      # - name: 변경사항 커밋 및 푸시
      #   run: |
      #     git config --global user.email "github-actions@github.com"
      #     git config --global user.name "github-actions"
      #     git add kubernetes/front-deploy.yaml
      #     if [ -z "$(git status --porcelain)" ]; then
      #       echo "No changes"
      #     else
      #       git commit -m "Update frontend image [skip ci]"
      #       git pull --rebase origin main
      #       git push origin main
      #     fi